### ISSUE TITLE
Not an issue just a heads up

### ISSUE THREAD

**Issue by axemwa** [TheBusyBiscuit/CS-CoreLib#51]
Just thought I'd confirm latest CS-CoreLib appears to be working in paper and spigot 1.13 and to suggest adding a 1.13 compatible tag to the latest file on devbukkit.org :)

**Comment by axemwa** [comment]
![image](https://user-images.githubusercontent.com/37608633/45104744-ee2ac000-b171-11e8-9fcc-cbc1dc5fd3e7.png)

**Comment by TheBusyBiscuit** [comment]
Updating a plugin takes much, much, much, much more effort than just changing a number.
And I can guarantee you that no matter how thoroughly you tested it, it will always require a lot of labour to update to the next Minecraft version, because even if it does not crash or throw any errors... It will simply not work and as this plugin does not do anything on its own and is just a library for other plugins, this only really becomes apparent when testing it in an actual field test with other plugins that are ported to the newest MC version.

Sorry but your confirmation is not true, it is not compatible with MC 1.13+

**Comment by axemwa** [comment]
in that case @smmmadden might wanna remove this one from your spreadsheet unless you have a better arguement?

**Comment by smmmadden** [comment]
Agreed, I'll remove it from the two 1.13.x columns and leave it for the others.  If a developer truly knows this isn't going to work, then it shouldn't be updated to say it does.  While we do limited testing and confirm server startup doesn't crash when it loads, it's not a 100% guarantee that when a call is made it won't work.  Somethings may and some may not.  So I'd prefer to side with caution on API's and not state it is available unless the developer clearly states it in their changelogs, overview tabs or elsewhere in the project.  Thanks for letting me know as well. -Steve :-)

**Comment by axemwa** [comment]
Fair enough I respect that...
