### ISSUE TITLE
Could not pass event InventoryClickEvent to CS-CoreLib vDEV - 50 (git 5a19465e)

### ISSUE THREAD

**Issue by ericbarbwire** [TheBusyBiscuit/CS-CoreLib#84]
Pastebin of server issue: https://pastebin.com/3bJ9Hep6
SlimeFun versions + Minecraft version:
Spigot 1.14.2
CS-CoreLib vDEV - 50 (git 5a19465e)
Slimefun vDEV - 102 (git 98cbec38)
SlimeXpansion v1.1.12
HotbarPets v1.1

**Comment by bverhoeven** [comment]
Hi there. 

This is actually a Slimefun issue which has been fixed in version 105 (git 7dae7) and up: https://github.com/TheBusyBiscuit/Slimefun4/pull/921. 

Could you please install [the latest build of Slimefun](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/) and see if you're still seeing this issue?
